apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler
  namespace: app
spec:
  restartPolicy: Never
  volumes:
  - name: vol
    hostPath:
      path: /hostpath33
  containers:
  - name: pv-recycler
    image: "nginx"
    command: ["/bin/sh", "-c", "echo 'Testing persistent storage' > /scrub/persistent.txt && sleep 300"] # <-- Fixed path
    volumeMounts:
    - name: vol
      mountPath: /scrub
